Key page suggestions
greymass/unicove pull request #259
Opened 2024-11-22 23:26 UTC by deansallinen

See comments

2024-11-22 23:47 UTC, aaroncox commented on src/routes/[network]/(explorer)/key/[publicKey]/+page.svelte
> +				<p>{data.publicKey}</p>
Yeah for sure.

```ts
const pubkey = PublicKey.from(data.publicKey)

console.log(String(pubkey))
// PUB_K1_6LPN8xGye86wme4PwqN8TSxAfGTQvqBcN5jGnURJPHyqn3a973

console.log(pubkey.toLegacyString())
// EOS6LPN8xGye86wme4PwqN8TSxAfGTQvqBcN5jGnURJPHyqnXqNAR
```

2024-11-25 18:57 UTC, dafuga commented on src/lib/components/elements/account.svelte
> +	let account: AccountState | undefined = $state();
We could have some kind of account cache store that is used to accomplish this, but we would probably always end up doing an API request since some of the resource values could be updated at any time. That store could immediately return an old version of the account data while the new data is loaded though which would allow the page load to be instant in this case.

2024-11-25 19:02 UTC, dafuga commented on src/lib/components/elements/account.svelte
> +	<div
This is a great idea! I think we should probably make a Preview component that would make it easier to have similar previews for other data types (for example, it would be great to have a transaction preview).

2024-11-25 19:06 UTC, dafuga commented on src/routes/[network]/(explorer)/key/[publicKey]/+page.ts
> +	const pubkey = PublicKey.from(String(params.publicKey));
This is going to break the page when an invalid key is used as a param. I think we either need to just pass the param down as a prop or we need to catch PublicKey errors here.

2024-11-25 19:09 UTC, dafuga commented on src/routes/[network]/(explorer)/key/[publicKey]/+page.svelte
> +<MultiCard>
❤️

2024-11-25 19:11 UTC, dafuga commented on src/routes/[network]/(explorer)/key/[publicKey]/+page.svelte
> +							<!-- <a href={`/eos/account/${account}`}>{account}</a> -->
I think we can just remove this.

2024-11-25 19:14 UTC, dafuga requested changes
I left you a few comments, but the main thing is that we need to handle the user passing an invalid key (right now it's causing a 500 error).

2024-11-25 19:19 UTC, deansallinen commented on src/lib/components/elements/account.svelte
> +	<div
I don't know how we would accomplish it with a generic component, but we can definitely do the same pattern with the `Transaction` component. Just need an idea of what to preview!

2024-11-25 19:46 UTC, deansallinen commented on src/routes/[network]/(explorer)/key/[publicKey]/+page.ts
> +	const pubkey = PublicKey.from(String(params.publicKey));
I think we _should_ be breaking the page on invalid key and sending the user to the `+error.svelte` 404 page. 

I don't know how we'd handle it otherwise. We can't really show anything else on the page if there's no key.

2024-11-25 21:04 UTC, dafuga commented on src/routes/[network]/(explorer)/key/[publicKey]/+page.ts
> +	const pubkey = PublicKey.from(String(params.publicKey));
From the point of view of the user, I think the way that it's being handled now that you added the 404 page is fine, but I don't think it's a good habit to let pages break like that (even if the user is taken to the 404 page). I would add a try catch block around the ` PublicKey.from(String(params.publicKey));` that sends users to the 404 page when an invalid key format error occurs. At some point, we're probably going to want to start monitoring our error logs and the less noise that is in there the better.

2024-11-25 22:04 UTC, dafuga commented on src/lib/components/elements/account.svelte
> +	<div
Either we would pass a trigger snippet that would allow you display the preview (passed as children prop) or the other thing we could do is have a generic preview component that would just take the data (in this case the account data) as a prop and the component would already know how to display the different data types (account, transaction, etc..). In any case, I don't think that we need to worry about this now.

2024-11-25 22:53 UTC, deansallinen commented on src/routes/[network]/(explorer)/key/[publicKey]/+page.ts
> -		subtitle: `${params.publicKey?.slice(0, 10)}...${params.publicKey?.slice(-10)}`,
I've removed it from here since we also have it just below in a card... doesn't make much sense to have a truncated version so close in the UI to the full version

2024-11-25 22:54 UTC, deansallinen commented on src/routes/[network]/(explorer)/key/[publicKey]/+page.ts
> +	const pubkey = PublicKey.from(String(params.publicKey));
I've made the error handling explicit. It's a good point, because this way we can switch on the error code to show different components in the `+error.svelte`

2024-11-25 23:38 UTC, dafuga approved these changes

2024-11-25 23:39 UTC, merged